<?php

?>

<div class="row form-group">
  <div class="col text-left">
    <button type="submit" name="submit"
            class="btn btn-primary"><?= $btnSubmit ?></button>
    <?php if (isset($indexRoute)) : ?>
      <a class="text-dark" href="<?= $indexRoute ?>">Retour</a>
    <?php endif; ?>
  </div>
  <?php if (isset($deleteRoute)) : ?>
    <div class="col text-right">
      <a class="btn btn-danger"
         href="<?= $deleteRoute ?>">Supprimer</a>
    </div>
  <?php endif; ?>
</div>
