<?php

?>
<div class="col-md-2 mt-2 mb-2">
  <form method="post">
    <div class="form-group">
      <label for="dataset"></label>
      <select class="form-control" id="dataset" name="dataset" size="2">
        <option value="cof">Fantasy</option>
        <option value="cocy">Cyberpunk</option>
      </select>
    </div>
    <div class="form-group">
      <button type="submit" name="submit" class="btn btn-primary">Valider</button>
    </div>
  </form>
</div>
